apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://notorious18rj:Cyborg%40031@cluster0.4yzwzfd.mongodb.net/todos?retryWrites=true&w=majority&appName=Cluster0