apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9ub3RvcmlvdXMxOHJqOkN5Ym9yZyU0MDAzMUBjbHVzdGVyMC40eXp3emZkLm1vbmdvZGIubmV0L3RvZG9zP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
